### PR TITLE
Enable Bash colors

### PR DESCRIPTION
**Pull request by olljanat**
Enable Bash colors to console like proposed on #30

### CODE REVIEW

**Review by tomaswarynyca — COMMENTED** [review]
Could you explain how the theme of colors would be?
- Do they come by default? 
- Do they have to be activated?
- Could you give a picture of how it would look

**Comment by olljanat** [comment]
Normally on Linux user profiles are created based on `/etc/skel` folder but because of way how console init works on BurmillaOS it does not happen without these additions.

To be exact those files contains Bash standard styles, etc settings and they are provided by its apt package  https://packages.debian.org/buster/amd64/bash/filelist Coloring text example on `ls -l` command is just one of the things which comes part of it.

Not front of computer now but you get idea example from this one https://linoxide.com/linux-command/set-colors-for-ls-command/

**Comment by olljanat** [comment]
Btw. You can test how it works by copying those files to user profile and login again to machine.

**Review by tomaswarynyca — APPROVED** [review]
Once the operation has been clarified, it is a brilliant contribution @olljanat

**Comment by dgiebert** [comment]
Should we create a page in the documentation page to keep track of all the changes for the upcoming release ?

**Comment by olljanat** [comment]
I published first release version now as it looks working correctly on all platforms which I tested and upgrade works too. It have up to date release notes on https://github.com/burmilla/os/releases/tag/v1.9.0

But we probably should write some migration guide #7 which can then explain more about how BurmillaOS differs now and will differ on future from RancherOS. So high level expiations can be found from [Projects](https://github.com/burmilla/os/projects) view.

**Pull request merged**
