### PR TITLE
make golang files to pass the latest go lints

### PR DESCRIPTION
**Pull request by h8liu**
- use constructors with named fields
- fix logf statements

the CI procedure was using a rather old golang compiler and golint.
These changes make the files be able to pass the latest golint.

The golint tool in use is not upgraded yet.

### CODE REVIEW

**Comment by olljanat** [comment]
Good idea. Let's try if I'm able to trigger pull request validation by closing and reopening this one.

**Comment by olljanat** [comment]
Looks that I got PR validation working. Can you update golint version now? And maybe it make sense actually update also Go version also.

**Comment by h8liu** [comment]
hmm, I think updating golint will require updating golang compiler, which will in turn require fixing some of the `go fmt` changes. My original plan is to do these in separate pull requests, but if you prefer to merge all those into one PR, I can also do it. Let me know.

**Comment by olljanat** [comment]
Ok. Then I merge this one already

**Review by olljanat — APPROVED** [review]

**Pull request merged**
